OBJS	= main.o
SOURCE	= main.c
HEADER	=
OUT	= main.out
CC	 = {{COMPILER}}
LIB      = {{LIBRARY_PATH}}
INC      = {{INCLUDE_PATH}}
FLAGS	 = -g -c -Wall {{FLAGS}}
LFLAGS	 = {{LINKER_FLAGS}}

all: $(OBJS)
	$(CC) -g $(OBJS) $(LIB) $(INC) -o $(OUT) $(LFLAGS)

main.o: main.c
	$(CC) $(FLAGS) $(LIB) $(INC) main.c -std=c11

clean:
	rm -f $(OBJS) $(OUT)

run: $(OUT)
	{{EXEC_PREFIX}}./$(OUT)